<?php

/**
 * UserLoginHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserLoginHistoryTable extends PluginUserLoginHistoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserLoginHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserLoginHistory');
    }
}