<?php

/**
 * AccountSecurity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    valueInvest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AccountSecurity extends BaseAccountSecurity
{
  public function getAvgBuyPrice()
  {
    if($this->getBuyQuantity()==0)return 0;
    return (-1)*floatval($this->getBuyAmount())/intval($this->getBuyQuantity());
  }
  public function getAvgSellPrice()
  {
    if($this->getSellQuantity()==0)return 0;
    return (-1)*floatval($this->getSellAmount())/intval($this->getSellQuantity());
  }
}
