<?php

/**
 * AccountSecurityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AccountSecurityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AccountSecurityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AccountSecurity');
    }
}