<?php

/**
 * HoldingHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HoldingHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HoldingHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HoldingHistory');
    }
}