<?php

/**
 * PerformanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PerformanceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PerformanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Performance');
    }
}