<?php

/**
 * Security
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    valueInvest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Security extends BaseSecurity
{
  public function getCprice()
  {
    $q = Doctrine_Query::create()
              ->from('Price p')
              ->where('p.security_id = ?', $this->id)
              ->having('max(p.date)');
    return $q->fetchOne();
  }
}
