<?php

/**
 * SyntheticTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SyntheticTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SyntheticTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Synthetic');
    }
}