# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        Value Invest ToolKid
    #description:  This is set of tools designed for value investors.
    #keywords:     value investor, finaince
    #language:     en
    #robots:       index, follow

  stylesheets: 
    - css960/reset: { media: all }
    - css960/960: { media: all }
    - css960/text: { media: all }
    - main

  javascripts:
    - jQuery/jquery-1.4.2.js

  has_layout:     true
  layout:         layout
