<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addaccountsecurity extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('account_security', array(
             'account_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'security_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'quantity' => 
             array(
              'type' => 'integer',
              'default' => 0,
              'length' => 8,
             ),
             'buy_quantity' => 
             array(
              'type' => 'integer',
              'default' => 0,
              'length' => 8,
             ),
             'sell_quantity' => 
             array(
              'type' => 'integer',
              'default' => 0,
              'length' => 8,
             ),
             'buy_amount' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'length' => 16,
             ),
             'sell_amount' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'length' => 16,
             ),
             'amount' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'length' => 16,
             ),
             'dividend' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'length' => 16,
             ),
             ), array(
             'indexes' => 
             array(
              'as_idx' => 
              array(
              'fields' => 
              array(
               0 => 'account_id',
               1 => 'security_id',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'account_id',
              1 => 'security_id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('account_security');
    }
}