<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addperformance extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('performance', array(
             'account_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'date' => 
             array(
              'type' => 'date',
              'notnull' => true,
              'length' => 25,
             ),
             'total_deposit' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'default' => '0.00',
              'notnull' => true,
              'length' => 16,
             ),
             'cash_balance' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'default' => '0.00',
              'notnull' => true,
              'length' => 16,
             ),
             'security_market_value' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'default' => '0.00',
              'notnull' => true,
              'length' => 16,
             ),
             'total_market_value' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'default' => '0.00',
              'notnull' => true,
              'length' => 16,
             ),
             'gain' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'default' => '0.00',
              'notnull' => true,
              'length' => 16,
             ),
             'time_weighted_return' => 
             array(
              'type' => 'decimal',
              'scale' => 7,
              'default' => '0.00',
              'notnull' => true,
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'account_id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('performance');
    }
}