<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addaccount extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('account', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'number' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => 64,
             ),
             'currency' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'USD',
              1 => 'RMB',
              2 => 'HKD',
              ),
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'default' => 'USD',
              'notnull' => true,
              'autoincrement' => false,
              'length' => NULL,
             ),
             'open_date' => 
             array(
              'type' => 'date',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => 25,
             ),
             'type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'ROTH',
              1 => 'IRA',
              2 => '401K',
              3 => 'RGLR',
              ),
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'default' => 'RGLR',
              'notnull' => true,
              'autoincrement' => false,
              'length' => NULL,
             ),
             'agency' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'default' => 'scottrade',
              'notnull' => true,
              'autoincrement' => false,
              'length' => 64,
             ),
             'last_record' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'last_compute' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
              'user_idx' => 
              array(
              'fields' => 
              array(
               0 => 'user_id',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('account');
    }
}