<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addalert extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('alert', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'max' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'length' => 16,
             ),
             'min' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'length' => 16,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('alert');
    }
}