<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddIndex extends Doctrine_Migration_Base
{
    public function up()
    {
      $options = array('fields' => array(
                                  'date',
                                  'account_id',
                                  'security_id'
                                  ),
                        'type' => 'unique');

      $this->addIndex('holding_history', 'ads_idx', $options);
        
    }

    public function down()
    {
      $this->removeIndex('holding_history', 'ads_idx');
   }
}