<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsecurity extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('security', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'symbol' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'notnull' => true,
              'length' => 32,
             ),
             'market' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'length' => 6,
             ),
             'google_id' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'unique' => true,
              'length' => 32,
             ),
             'yahoo_id' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'unique' => true,
              'length' => 32,
             ),
             'scottrade_id' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'unique' => true,
              'length' => 32,
             ),
             'name' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'length' => 64,
             ),
             'status' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'delisted',
              1 => 'listed',
              2 => 'suspend',
              3 => 'expired',
              ),
              'default' => 'listed',
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
              'ticker_idx' => 
              array(
              'fields' => 
              array(
               0 => 'symbol',
               1 => 'market',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('security');
    }
}