<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addtransaction extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('transaction', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'security_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'quantity' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'notnull' => true,
              'length' => 8,
             ),
             'price' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'default' => '0.00',
              'notnull' => true,
              'length' => 16,
             ),
             'trade_date' => 
             array(
              'type' => 'date',
              'notnull' => true,
              'length' => 25,
             ),
             'settled_date' => 
             array(
              'type' => 'date',
              'notnull' => false,
              'length' => 25,
             ),
             'amount' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'default' => '0.00',
              'notnull' => true,
              'length' => 16,
             ),
             'commission' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'default' => '0.00',
              'notnull' => true,
              'length' => 16,
             ),
             'description' => 
             array(
              'type' => 'string',
              'fixed' => 0,
              'notnull' => false,
              'length' => 255,
             ),
             'action_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'account_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'synthetic_id' => 
             array(
              'type' => 'integer',
              'notnull' => false,
              'length' => 8,
             ),
             'total_amount' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'default' => '0.00',
              'notnull' => true,
              'length' => 16,
             ),
             'total_quantity' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'notnull' => true,
              'length' => 8,
             ),
             'total_buy_amount' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'default' => '0',
              'notnull' => true,
              'length' => 16,
             ),
             'total_buy_quantity' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'notnull' => true,
              'length' => 8,
             ),
             'total_sell_amount' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'default' => '0',
              'notnull' => true,
              'length' => 16,
             ),
             'total_sell_quantity' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'notnull' => true,
              'length' => 8,
             ),
             'total_other_amount' => 
             array(
              'type' => 'decimal',
              'scale' => 4,
              'default' => '0.00',
              'notnull' => true,
              'length' => 16,
             ),
             'prev_tran' => 
             array(
              'type' => 'integer',
              'notnull' => false,
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('transaction');
    }
}