<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addPriceToHoldingHistory extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('holding_history', 'buy_price', 'decimal', '16', array(
             'scale' => '4',
             ));
        $this->addColumn('holding_history', 'price', 'decimal', '16', array(
             'scale' => '4',
             ));
        $this->addColumn('holding_history', 'dividend', 'decimal', '16', array(
             'scale' => '4',
             'default' => '0.00',
             'notnull' => '1',
             ));
        $this->addColumn('transaction','holding_history_id','integer','4', array(
            'default' => null,
            ));
        $this->addColumn('transaction','dividend','decimal', '16', array(
            'default' => '0.00',
            'scale' => '4'
            ));
        $this->renameColumn('transaction', 'total_amount', 'balance');
    }

    public function down()
    {
        $this->removeColumn('holding_history', 'buy_price');
        $this->removeColumn('holding_history', 'price');
        $this->removeColumn('holding_history', 'dividend');
        $this->removeColumn('transaction', 'holding_history_id');
        $this->removeColumn('transaction', 'dividend');
        $this->renameColumn('transaction', 'balance', 'total_amount');
    }
}
