generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: User Management
        display: [first_name, last_name,email_address,is_active,last_login]
      filter:  
        display: [first_name, last_name,email_address,is_active,last_login]
      form:    ~
      edit:    ~
      new:     ~
