User:
  actAs:
    Sluggable:
      unique: true
      fields: [first_name, last_name]
      canUpdate: true
      name: username
  columns:
    phonic_first: string
    phonic_last: string
  inheritance:
    type:             column_aggregation
    extends:          sfGuardUser
    keyField:         is_super_admin
    keyValue:         false
Account:
  actAs:
    Timestampable: ~
    Sluggable:
      unique: true
      fields: [agency, type]
      canUpdate: true
  connection: doctrine
  options:
    collate: utf8_unicode_ci
    charset: utf8
  tableName: account
  columns:
    number:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    currency:
      type: enum
      values: ['USD','RMB','HKD']
      fixed: false
      unsigned: false
      primary: false
      default: USD
      notnull: true
      autoincrement: false
    open_date:
      type: date
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    type:
      type: enum
      values: ['ROTH','IRA','401K','RGLR']
      fixed: false
      unsigned: false
      primary: false
      default: RGLR
      notnull: true
      autoincrement: false
    agency:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      default: scottrade
      notnull: true
      autoincrement: false
    last_record:
      type: timestamp
      default: null
    last_compute:
      type: timestamp
      default: null
    user_id:
      type: integer
      notnull: true
  indexes:
    user_idx:
      fields: ['user_id']
  relations:
    User:
      class: User
      local: user_id
      type: one
      foreignAlias: Accounts
      onDelete: CASCADE
    Transactions:
      autoComplete: true
      class: Transaction
      orderBy: trade_date ASC
      foreign: account_id
      local: id
      type: many
      foreignType: one
      orderBy: [security_id, trade_date DESC, id DESC]
    LatestTransaction:
      autoComplete: false
      class: Transaction
      orderBy: [ trade_date DESC, id DESC ]
      foreign: account_id
      local: id
      type: one
    Securities:
      class: Security
      foreignAlias: Accounts
      refClass: Transaction
      local: account_id
      foreign: security_id
Action:
  actAs:
    I18n:
      fields: [ name ]
  connection: doctrine
  tableName: action
  options:
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    name:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Transaction:
      local: id
      foreign: action_id
      type: many
Price:
  connection: doctrine
  tableName: price
  columns:
    security_id:
      type: integer
      notnull: true
    date:
      type: date
      notnull: true
    open:
      type: decimal(16)
      scale: 4
    close:
      type: decimal(16)
      scale: 4
    high:
      type: decimal(16)
      scale: 4
    low:
      type: decimal(16)
      scale: 4
    volume:
      type: integer
  actAs:
    Timestampable: ~
  relations:
    Security:
      local: security_id
      type: one
      foreign: id
      foreignAlias: Prices
      foreignType: many
  indexes:
    sdate:
      fields: [security_id, date]
      type: unique
Security:
  connection: doctrine
  tableName: security
  options:
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    symbol:
      type: string(32)
      fixed: false
      notnull: true
    market:
      type: string(6)
      fixed: false
    google_id:
      type: string(32)
      fixed: false
      unique: true
    yahoo_id:
      type: string(32)
      fixed: false
      unique: true
    scottrade_id:
      type: string(32)
      fixed: false
      unique: true
    name:
      type: string(64)
      fixed: false
    status:
      type: enum
      values: ['delisted','listed','suspend','expired']
      default: 'listed'
  indexes:
    ticker_idx:
      fields: ['symbol','market']
      type: unique
  relations:
    Accounts:
      class: Accounts 
      foreignAlias: Securities
      refClass: Transaction
      foreign: account_id
      local: security_id
    LatestPrice:
      autoComplete: false
      class: Price
      orderBy: [ date DESC, id DESC ]
      foreign: security_id
      local: id
      type: one
Synthetic:
  actAs:
    I18n:
      fields: [ name, description ]
    Sluggable:
      unique: true
      fields: [ name ]
      canUpdate: true
    Timestampable: ~
  connection: doctrine
  tableName: synthetic
  options:
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    name:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      default: Cash
      notnull: true
      autoincrement: false
    description:
      type: text
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
Transaction:
  actAs:
    MovingTotal:
      balance:
        column: amount
        totalColumn: balance
        orderBy: trade_date
        groupBy: [account_id]
      quantity:
        column: quantity
        totalColumn: total_quantity
        orderBy: trade_date
        groupBy: [account_id,security_id]
      total_buy_quantity:
        column: quantity
        totalColumn: total_buy_quantity
        orderBy: trade_date
        groupBy: [account_id,security_id]
        condition:
          column: action_id
          values: [1,46,47]
      total_buy_amount:
        column: amount
        totalColumn: total_buy_amount
        orderBy: trade_date
        groupBy: [account_id,security_id]
        condition:
          column: action_id
          values: [1,46,47]
      total_sell_quantity:
        column: quantity
        totalColumn: total_sell_quantity
        orderBy: trade_date
        groupBy: [account_id,security_id]
        condition:
          column: action_id
          values: [13,24,48,49]
      total_sell_amount:
        column: amount
        totalColumn: total_sell_amount
        orderBy: trade_date
        groupBy: [account_id,security_id]
        condition:
          column: action_id
          values: [13,24,48,49]
      dividend:
        column: amount
        totalColumn: dividend
        orderBy: trade_date
        groupBy: [account_id,security_id]
        condition:
          column: action_id
          values: [2]
      deposit:
        column: amount
        totalColumn: deposit
        orderBy: trade_date
        groupBy: [account_id,security_id]
        condition:
          column: action_id
          values: [9,29,109]
  connection: doctrine
  tableName: transaction
  options:
    collate: utf8_unicode_ci
    charset: utf8
  columns:
    security_id:
      type: integer
      notnull: true
    quantity:
      type: integer
      default: '0'
      notnull: true
    price:
      type: decimal(16)
      scale: 4
      default: '0.00'
      notnull: true
    trade_date:
      type: date
      notnull: true
    settled_date:
      type: date
      notnull: false
    amount:
      type: decimal(16)
      scale: 4
      default: '0.00'
      notnull: true
    commission:
      type: decimal(16)
      scale: 4
      default: '0.00'
      notnull: true
    description:
      type: string(255)
      fixed: false
      notnull: false
    action_id:
      type: integer
      notnull: true
    account_id:
      type: integer
      notnull: true
    synthetic_id:
      type: integer
      notnull: false
    balance:
      type: decimal(16)
      scale: 4
      default: '0.00'
      notnull: true
    total_quantity:
      type: integer
      default: '0'
      notnull: true
    total_buy_amount:
      type: decimal(16)
      scale: 4
      default: '0'
      notnull: true
    total_buy_quantity:
      type: integer
      default: '0'
      notnull: true
    total_sell_amount:
      type: decimal(16)
      scale: 4
      default: '0'
      notnull: true
    total_sell_quantity:
      type: integer
      default: '0'
      notnull: true
    total_other_amount:
      type: decimal(16)
      scale: 4
      default: '0.00'
      notnull: true
    dividend:
      type: decimal(16)
      scale: 4
      default: '0.00'
      notnull: true
  relations:
    Account:
      local: account_id
      foreign: id
      type: one
      foreignType: many
      foreignAlias: Transactions
    Action:
      local: action_id
      foreign: id
      type: one
      foreignType: many
      foreignAlias: Transactions
    Security:
      local: security_id
      foreign: id
      type: one
      foreignType: many
      foreignAlias: Transactions
    Synthetic:
      local: synthetic_id
      foreign: id
      type: one
      foreignType: many
      foreignAlias: Transactions
Performance:
  columns:
     account_id:
       type: integer
     date: 
       type: date
       notnull: true
     deposit:
       type: decimal(16)
       scale: 4
       default: '0.00'
       notnull: true
     cash_balance:
       type: decimal(16)
       scale: 4
       default: '0.00'
       notnull: true
     security_market_value:
       type: decimal(16)
       scale: 4
       default: '0.00'
       notnull: true
     total_market_value: #security+cash
       type: decimal(16)
       scale: 4
       default: '0.00'
       notnull: true
     gain: #total value - total deposit
       type: decimal(16)
       scale: 4
       default: '0.00'
       notnull: true
     time_weighted_return: #1.*
       type: decimal(8)
       scale: 7
       default: '0.00'
       notnull: true
  indexes:
    idx:
      fields: ['account_id','date']
      type: unique
